services:
  nginx:
    image: tpham1467/nginx:latest
    container_name: nginx
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api

  api:
    image: tpham1467/api
    container_name: api
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  