services:
  nginx:
    image: tpham1467/nginx:latest
    container_name: nginx
    build:
      context: ./src/Nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api

  api:
    image: tpham1467/api:latest
    container_name: api
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    networks:
      - app-network

  prometheus:
    image: tpham1467/prometheus:latest
    build:
      context: ./src/DashboardSystem
      dockerfile: prometheus.Dockerfile
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: tpham1467/grafana:latest
    build:
      context: ./src/DashboardSystem
      dockerfile: grafana.Dockerfile
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  prometheus_data:
  grafana_data: