worker_processes 3;

events { worker_connections 1024; }

http {
        sendfile on;
        large_client_header_buffers 4 32k;
         server {
             listen 80;
             client_max_body_size 30M;
             server_name api.ssast.tech www.api.ssast.tech;
              
             location = /scan-device/school-trips/check-action {
                     proxy_pass http://api;
             }
             location / {
                    return 301 https://$host$request_uri;
             }
         }
 
         server {
                 listen 443 ssl;
                 listen [::]:443 ssl;
                 server_name api.ssast.tech www.api.ssast.tech;
                 client_max_body_size 30M;
                 
                 ssl_certificate /etc/letsencrypt/live/api.ssast.tech/fullchain.pem;
                 ssl_certificate_key /etc/letsencrypt/live/api.ssast.tech/privkey.pem;
                 
                 location / {
                     proxy_set_header   Connection keep-alive;
                     proxy_set_header   Host api.ssast.tech;
                     proxy_set_header   X-Real-IP $remote_addr;
                     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                     proxy_set_header   X-Forwarded-Proto $scheme;
                     proxy_set_header   X-Forwarded-Host api.ssast.tech;
 
                     proxy_http_version 1.1;
                     proxy_set_header Upgrade $http_upgrade;
                     proxy_set_header Connection "upgrade";

                     proxy_pass         http://api;
                 }
                 
                 error_page 404 /NotFoundPage.html;
                 location = /NotFoundPage.html {
                         root /var/www/html;
                         internal;
                 }
         }
         
        server {
            listen 80;
            client_max_body_size 30M;
            server_name dashboard.ssast.tech www.dashboard.ssast.tech;

            return 301 https://$host$request_uri;
        }

        server {
                listen 443 ssl;
                listen [::]:443 ssl;
                server_name dashboard.ssast.tech www.dashboard.ssast.tech;
                client_max_body_size 30M;
                
                ssl_certificate /etc/letsencrypt/live/dashboard.ssast.tech/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/dashboard.ssast.tech/privkey.pem;
                
                location / {
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Scheme $scheme;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                        
                    proxy_pass         http://grafana:3000;
                }
                
                error_page 404 /NotFoundPage.html;
                location = /NotFoundPage.html {
                        root /var/www/html;
                        internal;
                }
        }        
}
