// <auto-generated />
using System;
using Api.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("class_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte>("Grade")
                        .HasColumnType("tinyint")
                        .HasColumnName("grade");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ManagedTeachers")
                        .HasColumnType("json")
                        .HasColumnName("managed_teachers");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int")
                        .HasColumnName("number_of_student");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Models.FileManagement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("file_name");

                    b.Property<float>("FileSize")
                        .HasColumnType("float")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("IsUploaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul)
                        .HasColumnName("is_uploaded");

                    b.Property<Guid?>("RelatedObjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("related_object_id");

                    b.Property<sbyte?>("RelatedObjectType")
                        .HasColumnType("tinyint")
                        .HasColumnName("related_object_type");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("s3_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UploadBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("uploaded_by");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("upload_date");

                    b.HasKey("Id");

                    b.ToTable("file_managements", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<TimeSpan>("AfternoonEndTime")
                        .HasColumnType("time")
                        .HasColumnName("afternoon_end_time");

                    b.Property<TimeSpan>("AfternoonStartTime")
                        .HasColumnType("time")
                        .HasColumnName("afternoon_start_time");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Images")
                        .HasColumnType("json")
                        .HasColumnName("images");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("MorningEndTime")
                        .HasColumnType("time")
                        .HasColumnName("morning_end_time");

                    b.Property<TimeSpan>("MorningStartTime")
                        .HasColumnType("time")
                        .HasColumnName("morning_start_time");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SchoolDescription")
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("school_description");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("school_name");

                    b.Property<sbyte>("SchoolType")
                        .HasColumnType("tinyint")
                        .HasColumnName("school_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("avatar_key");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("full_name")
                        .HasComputedColumnSql("CONCAT(first_name, ' ', last_name)");

                    b.Property<sbyte>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("last_name");

                    b.Property<int?>("LocationGroup")
                        .HasColumnType("int")
                        .HasColumnName("location_group");

                    b.Property<string>("ManagedBy")
                        .HasColumnType("json")
                        .HasColumnName("managed_by");

                    b.Property<decimal>("PickUpLat")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("pick_up_lat");

                    b.Property<decimal>("PickUpLng")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("pick_up_lng");

                    b.Property<string>("PickUpLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("pick_up_location");

                    b.Property<Guid?>("QrImageKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("qr_image_key");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SchoolId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("avatar_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("full_name")
                        .HasComputedColumnSql("CONCAT(first_name, ' ', last_name)");

                    b.Property<sbyte>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<sbyte>("AccountStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("account_status");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DetailAddress")
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("detail_address");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("first_name");

                    b.Property<sbyte>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name");

                    b.Property<sbyte>("UserType")
                        .HasColumnType("tinyint")
                        .HasColumnName("user_type");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("user_type_name");

                    b.Property<string>("discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("discriminator").HasValue("user");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Domain.Models.Driver", b =>
                {
                    b.HasBaseType("Api.Domain.Models.User");

                    b.Property<string>("DriverInformationImage")
                        .HasColumnType("json")
                        .HasColumnName("driver_information_image");

                    b.Property<DateTimeOffset?>("LastCheckDrivingLicense")
                        .HasColumnType("datetime")
                        .HasColumnName("last_check_driving_license");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("license_number");

                    b.Property<sbyte?>("VehicleType")
                        .HasColumnType("tinyint")
                        .HasColumnName("vehicle_type");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("json")
                        .HasColumnName("verified_by");

                    b.HasDiscriminator().HasValue("driver");
                });

            modelBuilder.Entity("Api.Domain.Models.Parent", b =>
                {
                    b.HasBaseType("Api.Domain.Models.User");

                    b.Property<string>("RelationshipWithStudents")
                        .HasColumnType("json")
                        .HasColumnName("relationship_with_students");

                    b.HasDiscriminator().HasValue("parent");
                });

            modelBuilder.Entity("Api.Domain.Models.SchoolPerson", b =>
                {
                    b.HasBaseType("Api.Domain.Models.User");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("school_id");

                    b.HasIndex("SchoolId");

                    b.HasDiscriminator().HasValue("school_person");
                });

            modelBuilder.Entity("Api.Domain.Models.Class", b =>
                {
                    b.HasOne("Api.Domain.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Api.Domain.Models.Teacher", null)
                        .WithMany("ManagedClasses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Api.Domain.Models.Student", b =>
                {
                    b.HasOne("Api.Domain.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Api.Domain.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Api.Domain.Models.Teacher", b =>
                {
                    b.HasOne("Api.Domain.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Api.Domain.Models.SchoolPerson", b =>
                {
                    b.HasOne("Api.Domain.Models.School", "School")
                        .WithMany("SchoolPersons")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Api.Domain.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Api.Domain.Models.School", b =>
                {
                    b.Navigation("SchoolPersons");
                });

            modelBuilder.Entity("Api.Domain.Models.Teacher", b =>
                {
                    b.Navigation("ManagedClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
