name: CI/CD for .NET with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create appsettings.json file from secrets
        run: echo '${{ secrets.APPSETTINGS_JSON }}' > src/Api/appsettings.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Compose
        run: docker compose build
      
      - name: Remove appsettings.json file after build
        run: rm -f src/Api/appsettings.json

      - name: Push Docker Image to Docker Hub
        run: docker compose push

  deploy:
    name: Deploy to Production
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Copy docker-compose.yml to Production
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "compose.yaml"
          target: "temp"
          strip_components: 0
            
      - name: SSH to Production & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Logging into Docker Hub on production..."
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "Navigating to project directory..."
            cd temp

            echo "Pulling latest Docker images..."
            docker compose pull

            echo "Deploying with Docker Compose..."
            docker compose up -d --remove-orphans

            echo "Cleaning up unused images..."
            docker image prune -f
